### PR TITLE
Feature/topic 13

### PR DESCRIPTION
**Pull request by estherwafula**

### CODE REVIEW

**Comment by estherwafula** [comment]
@shimichael9@
Please review this work.

**Comment by estherwafula** [comment]
@shiundumichael
please review my work

**Comment by shiundumichael** [comment]
Please observe the punctuation marks

**Comment by shiundumichael** [comment]
@michaelclapham

**Comment by shiundumichael** [comment]
@michaelclapham 
I think Esthers work needs the punctuation marks to be properly put.
The matter of different sections with different colors is also an issue but you said you will fix it later.

**Pull request merged**
