### PR TITLE
Adding Topic 12 - Keeping children safe online

### PR DESCRIPTION
**Pull request by maxwellfundi**
@michaelclapham  this replaces #15

### CODE REVIEW

**Comment by maxwellfundi** [comment]
In addition, we have the bottom part that i find it has buttons and links to other things that has not been added in other topics from before. 
image
Has this part been left intentionally ? I think having those links will be useful.

**Comment by maxwellfundi** [comment]
@michaelclapham in addition the footer of the tip sheets are the funders/partners . I can guess they would like to have the footer with the logos for the partners. what do you think

**Comment by maxwellfundi** [comment]
I have tried making them as similar as possible. 

image

What do you think @michaelclapham , If this is okay then the team can jump in this afternoon.

**Comment by maxwellfundi** [comment]
@barbra2020 Please review this

**Comment by praise-ebe** [comment]
@sylviawakoli
I request you to review for me

**Comment by sylviawakoli** [comment]
@praise-ebe 
I have seen no mistake

**Comment by maxwellfundi** [comment]
@michaelclapham  and one more thing, should everyone add these buttons at the bottom of the tip sheets?

**Comment by maxwellfundi** [comment]
@michaelclapham  I have just found out what some of the issues are with the ones that have failed to deploy properly. It is the difference in the auto generated files. Shall we keep our package managers consistent to avoid these issues. 

`3:22:45 PM: Installing NPM modules using Yarn version 1.17.0
3:22:45 PM: yarn install v1.17.0
3:22:45 PM: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.`

**Pull request merged**
