### PR TITLE
Adding the footer button on family harmony at home

### PR DESCRIPTION
**Pull request by sylviawakoli**

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@sylviawakoli  this looks good, however the blob need to change to the one on the tip sheets. Please find the correct blob and add it here. @michaelclapham could you re-share the blobs?

**Review by maxwellfundi — APPROVED** [review]
The blobs needs to be changed.

**Comment by maxwellfundi** [comment]
@sylviawakoli  Check for the blobs here - https://drive.google.com/drive/folders/1RMbvwjg1wcxjCzXhyrZcP37rqbVPIkOu and make sure to add the blob respective to your topic. 
Additionally make sure you add the blobs that are not more than 1mb

**Comment by michaelclapham** [comment]
@maxwellfundi Once again we'll deal with the blob images in a separate PR.

**Pull request merged**
