### PR TITLE
Feature/parenting teen

### PR DESCRIPTION
**Pull request by brendawafula**

### CODE REVIEW

**Comment by brendawafula** [comment]
@bmootian@gmail.com peer to peer

**Comment by brendawafula** [comment]
@barbra2020

**Comment by brendawafula** [comment]
@barbra2020 peer to peer review

**Comment by barbramootian** [comment]
@brendawafula have a peer to peer  review in my work

**Comment by barbramootian** [comment]
@brendawafula ,@michaelclapham
change the blobs to fit like the one in tip sheet
Also change the color 
One blobs before the title promote kindness and compassion the the other blob

**Pull request merged**
