### PR TITLE
Adding Topic 15- Feature parenting for a new baby

### PR DESCRIPTION
**Pull request by barbramootian**

### CODE REVIEW

**Comment by barbramootian** [comment]
@wotiabrenda25@gmail.com

**Comment by barbramootian** [comment]
@brendawafula  review my work

**Comment by brendawafula** [comment]
@barbra2020 and @michaelclapham 
Barbra please look on the background colour on subtopic "Be gentle with..........." on demo should be the same with that on covid-19-parenting App.

**Comment by brendawafula** [comment]
@barbra and @michaelclapham 
Please Barbra check on the blobs they are not the same one blob is sitted while the other is pushing some blocks.

**Pull request merged**
