### PR TITLE
Feature/family budgeting topic 11

### PR DESCRIPTION
**Pull request by estherwafula**

### CODE REVIEW

**Comment by estherwafula** [comment]
@bmotian@gmail.com
please have a review of the work of the topic-11 of the parenting app

**Review by shiundumichael — COMMENTED** [review]
Please put the sections as suggested by Michael.
Please observe the punctuation marks keenly.

**Comment by estherwafula** [comment]
@babra2020
please review my work

**Comment by estherwafula** [comment]
@barbra2020

**Comment by estherwafula** [comment]
@shiundumichael , @michaelclapham
Delete the empty spaces without writings.
Separate the following topics with different colors
           1.Movement games
           2.Memory game
           3.Singing

**Comment by estherwafula** [comment]
@michaelclapham
Conflicts have been resolved

**Comment by maxwellfundi** [comment]
@michaelclapham  please merge this.

**Pull request merged**
